package Objects;

public class Object_Ordbok_Miniatyrer extends Object_Ordbok_Old {

	public void FyllOrdbok() {
		int X = 0;
		
		Ord[X].Ordet = "miniatyr";
		Ord[X].Value = 20*2;
		X++;
		Ord[X].Ordet = "miniature";
		Ord[X].Value = 20*2;
		X++;
		Ord[X].Ordet = "miniatyr";
		Ord[X].Value = 20*2;
			X++;
		Ord[X].Ordet = "Casting";
		Ord[X].Value = 6*2;
			X++;
		Ord[X].Ordet = "conversion";
		Ord[X].Value = 10*2;
			X++;
		Ord[X].Ordet = "Pegasus";
		Ord[X].Value = 5*2;
			X++;
		Ord[X].Ordet = "Unicorn";
		Ord[X].Value = 5*2;
			X++;
		Ord[X].Ordet = "Stencil";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "BlackScorpionMiniatures";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Black Scorpion Miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "CoatD’Arms";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Coat D’Arms";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "Cmon";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "CoolMiniOrNot";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Cool Mini Or Not";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "CrocodileGames";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Crocodile Games";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "TyphonWarrior";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Typhon Warrior";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "DarkSwordMiniatures";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Dark Sword Miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "DragonbloodMiniatures";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Dragonblood Miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "DwarvenForge";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Dwarven Forge";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "FenryllMiniatures";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Fenryll Miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "ForgeWorld";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Forge World";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "GamesWorkshop";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Games Workshop";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Citadel";
		Ord[X].Value = 8*2;
			X++;
		Ord[X].Ordet = "Warhammer";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "BrettonianPegasus";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Brettonian Pegasus";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "ChaosKnight";
		Ord[X].Value = 8*2;
			X++;
		Ord[X].Ordet = "Chaos Knight";
		Ord[X].Value = 8*2;
		X++;
		Ord[X].Ordet = "ChaosMarauderChampion";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Chaos Marauder Champion";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "ChaosMarauderHorseman";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Chaos Marauder Horseman";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "ChaosWarrior";
		Ord[X].Value = 8*2;
			X++;
		Ord[X].Ordet = "Chaos Warrior";
		Ord[X].Value = 8*2;
			X++;
		Ord[X].Ordet = "Chimera";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "ColdOneKnightChampion";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Cold One Knight Champion";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "DarkElfColdOneKnight";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Dark Elf Cold One Knight";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "HighElfSilverHelm";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "High Elf Silver Helm";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "HighElvesPrinceonGriffon";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "High Elves Prince on Griffon";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "KhemrianWarsphinx";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Khemrian Warsphinx";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "HirtsArts";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Hirts Arts";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "HitechMiniatures";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Hitech Miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "MagnificentEgos";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Magnificent Egos";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "GaladonmountedonRose";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Galadon mounted on Rose";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "MaidenheadMiniatures";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Maidenhead Miniatures";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Mirliton";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "PrivateerPress";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Privateer Press";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Warmachine";
		Ord[X].Value = 9*2;
			X++;
		Ord[X].Ordet = "Rackham";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "RalPartha";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Ral Partha";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "ReaperMiniatures";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Reaper Miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "DarkHeavenLegends";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Dark Heaven Legends";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "Sword";
		Ord[X].Value = 5*2;
			X++;
		Ord[X].Ordet = "Schleich";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "SciborMiniatures";
		Ord[X].Value = 8*2;
			X++;
		Ord[X].Ordet = "Scibor Miniatures";
		Ord[X].Value = 8*2;
			X++;
		Ord[X].Ordet = "Shadowforge";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "SodaPopMiniatures";
		Ord[X].Value = 6*2;
			X++;
		Ord[X].Ordet = "Soda Pop Miniatures";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "StudioMcVey";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Studio McVey";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "TaleofWar";
		Ord[X].Value = 6*2;
			X++;
		Ord[X].Ordet = "Tale of War";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "The Army Painter";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "The Army Painter";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Troll Outpost";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Warlord Games";
		Ord[X].Value = 16*2;
			X++;
		Ord[X].Ordet = "Scenery";
		Ord[X].Value = 3*2;
			X++;
		Ord[X].Ordet = "Diorama";
		Ord[X].Value = 3*2;
			X++;
		Ord[X].Ordet = "Woodland Scenics";
		Ord[X].Value = 10*2;
			X++;
		Ord[X].Ordet = "Wargames";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Wargaming";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Fantasy";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Ancient";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Egypt";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Horse";
		Ord[X].Value = 3*2;
		X++;
		Ord[X].Ordet = "Blue Moon";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Monster";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Terrain";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Acheson";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Primaeval";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "Armorcast";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Mega Minis";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "Sandra Garrity";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "Vampire";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Wood elf";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "Dark elf";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "High elf";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = " elf ";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Wood elves";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "Dark elves";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "High elves";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "elves";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Black Scorpion";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Confrontation";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "Rackham";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "Dark age";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Blacksun";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Chaos Demon";
		Ord[X].Value = 8*2;
		X++;
		Ord[X].Ordet = "kings of war";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "legion of everblight";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "Lord of the rings";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "lotr";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "Malifaux";
		Ord[X].Value = 8*2;
		X++;
		Ord[X].Ordet = "Menoth";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "Empire";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Bretton";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "Chaos";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Warrior";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "Beast";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "Caesar";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "Wizard";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "Blackbird";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "wolf";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "wolves";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "greece";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "greek";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "rome";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "roman";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "persia";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "hoplite";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "d&d";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "raider";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = " sea ";
		Ord[X].Value = 3*2;
		X++;
		Ord[X].Ordet = "tyranid";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "adventure";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "lothlorien";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "isengard";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "moria";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "numenor";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "rhun";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "mordor";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "gondor";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "fellowship";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "rohan";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "iron hills";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "harad";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "khand";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "roleplaying";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "knight";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "paladin";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "dark sword";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "darksword";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "enigma";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "dungeon";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "forge";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "resin";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "metal";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = " lead ";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "dragon";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "visions in fantasy";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "lord";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "angel";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "daemon";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "female";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "converting";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "casting";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "bitz";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "kabuki";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "kingdom death";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "chasm keeper miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "warploque miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "max models";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "miniature heroes";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "gw";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "banelords";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "banelegions";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "master miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "taban miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "knight model";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "arcana miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "raging heroes";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "hunter";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "griffon";
		Ord[X].Value = 8*2;
		X++;
		Ord[X].Ordet = "island of blood";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "storm of magic";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "mordheim";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "medieval";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "crusade";
		Ord[X].Value = 5*2;
		X++;
		Ord[X].Ordet = "valkyr";
		Ord[X].Value = 8*2;
		X++;
		Ord[X].Ordet = "unassembled";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "spear";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "archer";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "citadel miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "beastman";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "beastmen";
		Ord[X].Value = 10*2;
		X++;
		Ord[X].Ordet = "bull";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "mounted";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "hero";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "minotaur";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "cavalry";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "grenadier";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "grenadier miniatures";
		Ord[X].Value = 16*2;
		X++;
		Ord[X].Ordet = "rhino";
		Ord[X].Value = 3*2;
		X++;
		Ord[X].Ordet = "amazon";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "cat";
		Ord[X].Value = 1*2;
		X++;
		Ord[X].Ordet = "rider";
		Ord[X].Value = 4*2;
		X++;
		Ord[X].Ordet = "chariot";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "tiger";
		Ord[X].Value = 3*2;
		X++;
		Ord[X].Ordet = "hippogriff";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "winged";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "manticore";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "chimera";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "raptor";
		Ord[X].Value = 8*2;
		X++;
		Ord[X].Ordet = "warchief";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "armored";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "armoured";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "armoured dragon";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "armored dragon";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "bear";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "centaur";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "eagle";
		Ord[X].Value = 6*2;
		X++;
		Ord[X].Ordet = "fighter";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "ranger";
		Ord[X].Value = 7*2;
		X++;
		Ord[X].Ordet = "whfb";
		Ord[X].Value = 10*2;
		
		X++;
		Ord[X].Ordet = "dice";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "round base";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "card";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "comic";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "playstation";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "sony";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "dvd";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "nintendo";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "microsoft";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "blog";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "motor";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "classified";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "paint";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "ww";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "old west";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "colonial";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "book";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "blood bowl";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "battletech";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "base";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "civil";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "20 mm";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "2 mm";
		Ord[X].Value = -15;
		X++;
		Ord[X].Ordet = "12 mm";
		Ord[X].Value = -7;
		X++;
		Ord[X].Ordet = "15 mm";
		Ord[X].Value = -7;
		X++;
		Ord[X].Ordet = "6 mm";
		Ord[X].Value = -15;
		X++;
		Ord[X].Ordet = "barack obama";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "harrison ford";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "sex";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "drunk";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "celebs";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "sausage";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "show";
		Ord[X].Value = -1;
		X++;
		Ord[X].Ordet = "broadcasting";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "watch";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "episode";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "schedule";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "dance";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "audition";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "idol";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "tonight";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "final fantasy";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "tank";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "missile";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "ww2";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "wwII";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "vehicle";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "ammo";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "rocket";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "star trek";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "axis";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "dexter";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "family";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "harry potter";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "simpsons";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "movies";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "manga";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "cartoon";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "golden demon";
		Ord[X].Value = 16;
		X++;
		Ord[X].Ordet = "crystal brush";
		Ord[X].Value = 16;
		X++;
		Ord[X].Ordet = "web hosting";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "sports";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "finance";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "maps";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "domain";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "command and conquer";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "trailer";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "tiberium";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "auto";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "moto";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "parfume";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "Céramiques";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "dvd";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "cinema";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "photo";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "musique";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "Téléphonie";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "gastronom";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "monitor";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "hardware";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "elektronik";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "foto";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "video";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "konsol";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "handy";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "shoe";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "handbag";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "fashion";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "kids";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "baby";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "business";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "industrial";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "camera";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "clothing";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "doll";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "dollhouse";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "health";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "beauty";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "musical";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = " pet ";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "music";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "pottery";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "american dad";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "american";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "american idol";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "breaking in";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "girlfriend";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "trivia";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = " boot ";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = " karte";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = " kind ";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet =  "film ";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "barbie";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "saga";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "sin city";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "greys anatomy";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "csi";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "guitar";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "grudge";
		Ord[X].Value = -20;
		X++;
		Ord[X].Ordet = "poetry";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "pizza";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "olje";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "industri";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "oljeindustri";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "landsforening";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "aktivitet ";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "sokkel";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "norsk";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "gass";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "petroleum";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "dollshouse";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "wedding";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = " doll ";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = " dolls ";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = " bride ";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "children";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "charity";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "production";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "offload";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "network";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "matrix";
		Ord[X].Value = -5;
		X++;
		Ord[X].Ordet = "continental shelf";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "protection";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "fire protection";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "risk management";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "site safety";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "helicopter";
		Ord[X].Value = -10;
		X++;
		Ord[X].Ordet = "handover";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "documentation";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "Your browser sent a request that this server could not understand.";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "We apologize for the inconvenience. Please contact the webmaster/ tech support immediately to have them rectify this.";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "You don't have permission to access / on this server.";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "The requested URL / was not found on this server. That’s all we know.";
		Ord[X].Value = -30;
		X++;
		Ord[X].Ordet = "Make sure you did not mis-type the URL.";
		Ord[X].Value = -30;
		
		
	}
}
